#!/bin/bash
# moving supported libraries  and utilities in user lib and bin.

cp ./libgd.so.3.0.20200 /usr/local/lib/
cp ./libhpdf-2.4.0dev.so /usr/local/lib/
cp ./libpng16.so.16.28.0 /usr/local/lib/
cp ./libsqlite3.so.0 /usr/local/lib/
cp ./libz.so.1.2.11 /usr/local/lib/
cp ./libzmq.so.5.1.3 /usr/local/lib/
cp ./libjson-c.so.3.0.0 /usr/local/lib/

ln -s /usr/local/lib/libgd.so.3.0.20200 /usr/local/lib/libgd.so.3
ln -s /usr/local/lib/libpng16.so.16.28.0 /usr/local/lib/libpng16.so.16
ln -s /usr/local/lib/libz.so.1.2.11 /usr/local/lib/libz.so.1
ln -s /usr/local/lib/libhpdf-2.4.0dev.so /usr/local/lib/libhpdf.so
ln -s /usr/local/lib/libsqlite3.so.0 /usr/local/lib/libsqlite3.so
ln -s /usr/local/lib/libzmq.so.5.1.3 /usr/local/lib/libzmq.so
ln -s /usr/local/lib/libzmq.so.5.1.3 /usr/local/lib/libzmq.so.5
ln -s /usr/local/lib/libjson-c.so.3.0.0 /usr/local/lib/libjson-c.so
ln -s /usr/local/lib/libjson-c.so.3.0.0 /usr/local/lib/libjson-c.so.3

#sudo ldconfig

cp ./gnuplot /usr/local/bin/
cp ./user_db_manager /usr/local/bin/


# creating user_db_config directory to store the DB Management file and calibration data config file.

mkdir /usr/local/bin/user_db_config
cp ./user_db_mgr_config.conf /usr/local/bin/user_db_config

# moving startup script and conf file in init directory

chmod +x ./user_db_manager.sh
cp ./user_db_manager.sh /etc/init.d/
sudo update-rc.d user_db_manager.sh remove
sudo update-rc.d -f user_db_manager.sh defaults 99 01
