#!/bin/bash
# moving supported libraries  and utilities in user lib and bin.

cp ./lib/libgd.so.3.0.20200 /usr/local/lib/
cp ./lib/libhpdf-2.4.0dev.so /usr/local/lib/
cp ./lib/libpng16.so.16.28.0 /usr/local/lib/
cp ./lib/libsqlite3.so.0 /usr/local/lib/
cp ./lib/libz.so.1.2.11 /usr/local/lib/
cp ./lib/libzmq.so.5.1.3 /usr/local/lib/
cp ./lib/libjson-c.so.3.0.0 /usr/local/lib/

ln -s /usr/local/lib/libgd.so.3.0.20200 /usr/local/lib/libgd.so.3
ln -s /usr/local/lib/libpng16.so.16.28.0 /usr/local/lib/libpng16.so.16
ln -s /usr/local/lib/libz.so.1.2.11 /usr/local/lib/libz.so.1
ln -s /usr/local/lib/libhpdf-2.4.0dev.so /usr/local/lib/libhpdf.so
ln -s /usr/local/lib/libsqlite3.so.0 /usr/local/lib/libsqlite3.so
ln -s /usr/local/lib/libzmq.so.5.1.3 /usr/local/lib/libzmq.so
ln -s /usr/local/lib/libzmq.so.5.1.3 /usr/local/lib/libzmq.so.5
ln -s /usr/local/lib/libjson-c.so.3.0.0 /usr/local/lib/libjson-c.so
ln -s /usr/local/lib/libjson-c.so.3.0.0 /usr/local/lib/libjson-c.so.3

#sudo ldconfig

cp ./lib/gnuplot /usr/local/bin/
cp -r ./include/* /usr/local/include/

# creating user_db_config directory to store the DB Management file and calibration data config file.

mkdir /usr/local/bin/user_db_config
cp ./user_db_mgr_config.conf /usr/local/bin/user_db_config
